
trigger:
- main

pool:
  name: MyPool

variables:
  solution: '**/*.sln'

steps:
  - task: NuGetToolInstaller@1
    displayName: 'Nuget Installation'

  - task: NuGetCommand@2
    displayName: 'Nuget restoreSolution'
    inputs:
      restoreSolution: '$(solution)'

  - task: VSBuild@1
    displayName: 'Build msbuildArgs'
    inputs:
      solution: '$(solution)'
      msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactstagingdirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'PublishBuildArtifacts Installation'
    inputs:
      PathtoPublish: "$(build.artifcatstagingdirectory)"
      ArtifactName: 'drop'
      publishLocation: 'Container'
    